#cloud-config:
package_update: true
package_upgrade: true

apt:
  preserve_sources_list: true
  sources:
    tailscale.list:
      source: "deb https://pkgs.tailscale.com/stable/ubuntu focal main"
      keyid: 2596A99EAAB33821893C0A79458CA832957F5868

packages: 
  - tailscale

runcmd:
  # ip forwarding must be enabled to act as a gateway
  - echo 'debug {0}'
  - echo 'net.ipv4.ip_forward = 1' | tee -a /etc/sysctl.conf
  - echo 'net.ipv6.conf.all.forwarding = 1' | tee -a /etc/sysctl.conf
  - sysctl -p /etc/sysctl.conf
  - tailscale up --authkey {0}